version: "3.8"
services:
  api:
    tty: true
    build:
      context: ./api/
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
    command: ash -c "rm -f /tmp/pids/server.pid && rails s -b '0.0.0.0'"
    ports:
      - 3000:3000
    links:
      - db
  db:
    image: mysql:8.0.26
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front/app:/usr/src/app
    command: "yarn dev"
    ports:
      - 8000:3000
volumes:
  bundle:
  mysql-data:
